### ISSUE TITLE
Fix character count depending on encoding

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/chatpro#6]
The character count of messages changes depending on the GSM encoding used. http://stackoverflow.com/questions/7103990/sms-messages-non-ascii-characters-encoding

**Comment by rowanseymour** [comment]
Does this mean that any message with an Arabic letter is limited to 70 chars rather than 140? If so then we can update the send form to switch its limit to 70 when it detects a non-ASCII character.

We definitely want to prevent messages from being split on the RapidPro side. Split messages don't work so well for group chat as only the first message will include the name: prefix.

**Comment by citizenrich** [comment]
Yes, as I understand it the messages that have even one non-ASCII character are then switched to 16-bit encoding (70 characters). This would also include the chat name. So, the approach described above would work.

**Comment by citizenrich** [comment]
Closing as stale.
